export const GET_COURSE_DETAIL_REQUEST = "GET_COURSE_DETAIL_REQUEST";
export const GET_COURSE_DETAIL_SUCCESS = "GET_COURSE_DETAIL_SUCCESS";
export const GET_COURSE_DETAIL_FAILURE = "GET_COURSE_DETAIL_FAILURE";

export const GET_COURSE_ENROLL_REQUEST = "GET_COURSE_ENROLL_REQUEST";
export const GET_COURSE_ENROLL_SUCCESS = "GET_COURSE_ENROLL_SUCCESS";
export const GET_COURSE_ENROLL_FAILURE = "GET_COURSE_ENROLL_FAILURE";

export const ENROLL_REQUEST = "ENROLL_REQUEST";
export const ENROLL_SUCCESS = "ENROLL_SUCCESS";
export const ENROLL_FAILURE = "ENROLL_FAILURE";

export const UN_ENROLL_REQUEST = "UN_ENROLL_REQUEST";
export const UN_ENROLL_SUCCESS = "UN_ENROLL_SUCCESS";
export const UN_ENROLL_FAILURE = "UN_ENROLL_FAILURE";

