export const ENROLL_REQUEST = "ENROLL_REQUEST";
export const ENROLL_SUCCESS = "ENROLL_SUCCESS";
export const ENROLL_FAILURE = "ENROLL_FAILURE";
export const CANCEL_ENROLL_REQUEST = "CANCEL_ENROLL_REQUEST";
export const CANCEL_ENROLL_SUCCESS = "CANCEL_ENROLL_SUCCESS";
export const CANCEL_ENROLL_FAILURE = "CANCEL_ENROLL_FAILURE";
